apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: meetinity-api-gateway
  labels:
    app: meetinity-api-gateway
    component: gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: meetinity-api-gateway-blue
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
